// packages/vue3/src/App.vue
<script setup lang="ts">
// import HelloWorld from './components/HelloWorld.vue'
import { ref } from 'vue'
import { FullEventCalendar } from './components/FullEventCalendar'
import { events } from '@full-event-calendar/test-events'
import { DailyGridPlugin } from '@full-event-calendar/daily-grid'
import { MonthGridPlugin } from '@full-event-calendar/month-grid'
import { WeeklyGridPlugin } from '@full-event-calendar/weekly-grid'
import { ListPlugin } from '@full-event-calendar/list/dist/index.js'
import '@full-event-calendar/core/dist/main.css'

const eventsList = ref(events)
const count = ref(0)
//@ts-ignore
function saySmt(ss) {
  console.log('sdsd', ss.data.ondataChange(new Date()))
}
// import
function eventUpdate(data: any) {
  console.log('on event update ', data)
  // eventsList.value.push(data.next.sourceEvent)
}

function AddEvent(data: any) {
  console.log('dataAdded', data)
  eventsList.value.push(data.sourceEvent)
}
const dateee = ref(new Date('Thu Aug 10 2023 15:00:0'))
setTimeout(() => {
  //dateee.value = new Date()
}, 4000)
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <button @click="count++">count</button>
  <FullEventCalendar
    :auto-update-event-on-change="true"
    :editable="true"
    v-model:events="eventsList"
    @eventUpdate="eventUpdate"
    stop-add-event
    :initial-date="dateee"
    :plugins="[DailyGridPlugin, MonthGridPlugin, WeeklyGridPlugin, ListPlugin]"
  >
    <template #dailyHeader="data"> daily header slot {{ data }} </template>
    <!-- <template #timeRange="{data}">{{ data.time }}</template> -->
    <template #addModal="{ data }">
      <div class="modaaaaal">
        this is a vue modal slot {{ data?.time?.start?.toString() }} --- {{ data?.time?.end?.toString() }}
        <div @click="data.saveModal">
          <button @click="AddEvent(data.time)">save</button>
        </div>
      </div>
    </template>
    <template #eventClick="{ data }">
      <div class="eventClickModal">{{ data }}</div>
    </template>
    <template #headerSlot="data">
      <button @click="count++">click</button> this is {{ count }} a test {{ data }}
    </template>
    <template #headerDateSlot="data">
      <button @click="count++">click</button> this is {{ count }} a test {{ data }}
    </template>
    <template #todayBtn>
      <button>go to mee</button>
    </template>
    <template #goBackDate>
      <button>عقب</button>
    </template>
    <template #goForwardDate>
      <button>جلو</button>
    </template>
    <!-- <template #gridDropDown="DATA">
      <button  >گرید</button>  {{ DATA }}
    </template> -->
  </FullEventCalendar>
</template>

<style scoped>
.modaaaaal {
  width: 200px;
  background-color: red;
}

.eventClickModal {
  width: 200px;
  background-color: green;
}

.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// packages/react/src/App.tsx
import { useEffect, useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
import { FullEventCalendar } from './components/FullEventCalendar'
import { events } from '@full-event-calendar/test-events'

import { DailyGridPlugin } from '@full-event-calendar/daily-grid'
import { MonthGridPlugin } from '@full-event-calendar/month-grid'
import { WeeklyGridPlugin } from '@full-event-calendar/weekly-grid'
import { ListPlugin } from '@full-event-calendar/list/dist/index.js'
import '@full-event-calendar/core/dist/main.css'
//@ts-nocheck
function AddModalSlot(props) {
  return <div>daily header slot</div>
}
function EventClickSlot(props) {
  console.log(props)
  return <div className="eventClick"> i dont like react {props?.eventData?.start.toString()} </div>
}

function TestSlot(props) {
  // console.log(props)
  return <div>this is a test slot</div>
}
function EventaddModalSlot(props) {
  function saveBtnClik() {
    props.saveModal()
    props.someProp(props.eventData.sourceEvent)
  }
  return (
    <div className="eventClick" style={{ background: 'red' }}>
      {' '}
      i dont like react
      {props?.eventData?.start.toString()}
      <button className="" onClick={saveBtnClik}>
        SAVE
      </button>
    </div>
  )
}
function App() {
  const [count, setCount] = useState(new Date('Thu Aug 10 2023 15:00:0'))
  const [eventsR, setEvents] = useState(events)
  // setTimeout(() => {
  //   setCount(new Date())
  // }, 5000);

  function asaveEv(ev) {
    let arr = [...eventsR, ev]

    setEvents(arr)
  }
  useEffect(() => {
    // console.log('download',eventsR)
  }, [eventsR])

  console.log('mount')
  const onEveUpdate = (data) => {
    console.log(eventsR, data)
    const eventsCopy = [...eventsR]
    let ind = eventsCopy.findIndex((item) => item.id === data.id)
    eventsCopy[ind] = data.next.sourceEvent
    setEvents(eventsCopy)
    // console.log(eventsR)
    // setTimeout(() => {
    //   console.log(eventsR)
    // }, 2000);
  }
  function eventStoped({ event }) {
    console.log('styped', event)
  }
  function eventAdd({ event }) {
    // const eventsCopy = [...eventsR]
    // eventsCopy.push(event.sourceEvent)
    // setEvents(eventsCopy)
  }

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <FullEventCalendar
        plugins={[DailyGridPlugin, WeeklyGridPlugin, MonthGridPlugin, ListPlugin]}
        dailyHeader={<AddModalSlot />}
        events={eventsR}
        eventClick={<EventClickSlot someProp={asaveEv} />}
        autoUpdateEventOnChange={false}
        editable={true}
        addModal={<EventaddModalSlot someProp={asaveEv} />}
        stopAddEvent={true}
        initialDate={count}
        eventAdd={eventAdd}
        eventUpdate={onEveUpdate}
        addEventStoped={eventStoped}
        headerDateSlot={<TestSlot />}
        gridDropDown={<TestSlot />}
        goForwardDate={<TestSlot />}
        goBackDate={<TestSlot />}
        todayBtn={<TestSlot />}
      ></FullEventCalendar>
    </>
  )
}

// gridDropDown={onEveUpdate}
// goForwardDate={testSlot}
// goBackDate={testSlot}
// todayBtn={testSlot}
// headerDateSlot={testSlot}
export default App
